//
//  TopRatedRepositoriesPresenter.swift
//  TopRatedRepositories
//
//  Created by Mauro Sasso Coletes on 11/04/19.
//  Copyright (c) 2019 MSC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TopRatedRepositoriesPresentationLogic {
    func reloadTable()
    func displayError(type: TopRatedRepositoriesModels.errors, tryAgainAction: EmptyClosure?)
    func presentEndRefreshControl()
    func presentViewModelFromModel(repository: Repository) -> TopRatedRepositoriesModels.ViewModel?
}

class TopRatedRepositoriesPresenter: TopRatedRepositoriesPresentationLogic {
    
    weak var viewController: TopRatedRepositoriesDisplayLogic?

    func reloadTable() {
        viewController?.reloaTable()
    }
    
    func displayError(type: TopRatedRepositoriesModels.errors, tryAgainAction: EmptyClosure?) {
        switch type {
        case .noInternet:
            viewController?.displayError(message: R.string.topRatedRepositories.noInternetConnectionMessage(), actionButtonTitle: nil, tryAgainAction: nil)
        default:
            viewController?.displayError(message: R.string.topRatedRepositories.tryAgainMessage(), actionButtonTitle: R.string.topRatedRepositories.tryAgainActionTitle(), tryAgainAction: tryAgainAction)
        }
    }
    
    func presentEndRefreshControl() {
        viewController?.endRefreshControl()
    }
    
    func presentViewModelFromModel(repository: Repository) -> TopRatedRepositoriesModels.ViewModel? {
        return TopRatedRepositoriesModels.ViewModel(name: repository.name ?? "", stars: repository.stargazersCount ?? 0, ownerName: repository.owner?.login ?? "", ownerPhotoURL: URL(string: repository.owner!.avatarUrl!)!)
    }
}
