//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `topRepositories.json`.
    static let topRepositoriesJson = Rswift.FileResource(bundle: R.hostingBundle, name: "topRepositories", pathExtension: "json")
    
    /// `bundle.url(forResource: "topRepositories", withExtension: "json")`
    static func topRepositoriesJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.topRepositoriesJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `github_icon`.
    static let github_icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "github_icon")
    /// Image `stars`.
    static let stars = Rswift.ImageResource(bundle: R.hostingBundle, name: "stars")
    /// Image `userLogo`.
    static let userLogo = Rswift.ImageResource(bundle: R.hostingBundle, name: "userLogo")
    
    /// `UIImage(named: "github_icon", bundle: ..., traitCollection: ...)`
    static func github_icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.github_icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "stars", bundle: ..., traitCollection: ...)`
    static func stars(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.stars, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "userLogo", bundle: ..., traitCollection: ...)`
    static func userLogo(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.userLogo, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.topRatedRepositories` struct is generated, and contains static references to 6 localization keys.
    struct topRatedRepositories {
      /// Value: No internet connection
      static let noInternetConnectionMessage = Rswift.StringResource(key: "noInternetConnectionMessage", tableName: "TopRatedRepositories", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: OK
      static let okActionTitle = Rswift.StringResource(key: "okActionTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Ops
      static let warningTitle = Rswift.StringResource(key: "warningTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Something went wrong. Please try again!
      static let tryAgainMessage = Rswift.StringResource(key: "tryAgainMessage", tableName: "TopRatedRepositories", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Top Rated Repositories
      static let topRepositoriesTitle = Rswift.StringResource(key: "topRepositoriesTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, locales: [], comment: nil)
      /// Value: Try Again
      static let tryAgainActionTitle = Rswift.StringResource(key: "tryAgainActionTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, locales: [], comment: nil)
      
      /// Value: No internet connection
      static func noInternetConnectionMessage(_: Void = ()) -> String {
        return NSLocalizedString("noInternetConnectionMessage", tableName: "TopRatedRepositories", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: OK
      static func okActionTitle(_: Void = ()) -> String {
        return NSLocalizedString("okActionTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Ops
      static func warningTitle(_: Void = ()) -> String {
        return NSLocalizedString("warningTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Something went wrong. Please try again!
      static func tryAgainMessage(_: Void = ()) -> String {
        return NSLocalizedString("tryAgainMessage", tableName: "TopRatedRepositories", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Top Rated Repositories
      static func topRepositoriesTitle(_: Void = ()) -> String {
        return NSLocalizedString("topRepositoriesTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, comment: "")
      }
      
      /// Value: Try Again
      static func tryAgainActionTitle(_: Void = ()) -> String {
        return NSLocalizedString("tryAgainActionTitle", tableName: "TopRatedRepositories", bundle: R.hostingBundle, comment: "")
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try launchScreen.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      static func validate() throws {
        if UIKit.UIImage(named: "github_icon", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'github_icon' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, *) {
        }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
